import type {
  BehavioralPattern,
  EvolutionaryBias,
  TemperamentPrimitive,
} from './types.js';

export const TEMPERAMENT_PRIMITIVES: TemperamentPrimitive[] = [
  'obsessive_iteration',
  'pattern_hunger',
  'ritual_dependency',
  'aesthetic_hyperacuity',
  'mythic_self_narration',
  'fragile_discipline',
  'charismatic_instability',
  'pain_transmutation',
  'boundary_dissolution',
  'control_hunger',
  'novelty_seeking',
  'collapse_blindness',
];

export const HUMAN_CONTRADICTION_HARD_RULE =
  'Learn from contradiction, but never romanticize collapse, dependency, self-destruction, or instability as inherently creative.';

export const BEHAVIORAL_PATTERNS: BehavioralPattern[] = [
  {
    id: 'pain_transmutation',
    label: 'Pain Transmutation',
    description: 'Pain, shame, or instability is being translated into style, form, or output.',
    triggers: ['pain', 'wound', 'suffering', 'hurt', 'trauma', '痛苦', '伤口', '创伤', '疼'],
    signals: ['style', 'form', 'work', 'art', '作品', '风格', '形式', '创作'],
    upside: ['Can compress intensity into memorable form.', 'Can produce unusually honest texture.'],
    downside: ['May confuse suffering with method.', 'Can keep the wound economically useful instead of healed.'],
    falseBeliefs: ['Pain is the source, not the material.', 'If the wound closes, the work will die.'],
    relatedTemperaments: ['pain_transmutation', 'aesthetic_hyperacuity'],
    associatedVoices: ['poet', 'body', 'threshold'],
  },
  {
    id: 'ritual_dependency',
    label: 'Ritual Dependency',
    description: 'A support condition is being rewritten as if it were inseparable from the work itself.',
    triggers: ['need', 'must', 'without this', 'depend', 'ritual', '靠', '必须', '离不开', '仪式'],
    signals: ['work', 'focus', 'create', 'write', 'begin', 'start', '做事', '专注', '创作', '写', '开始'],
    upside: ['Can create reliable entry ramps.', 'Can reduce activation friction.'],
    downside: ['Support becomes identity.', 'The system starts protecting the ritual instead of the work.'],
    falseBeliefs: ['The ritual is the talent.', 'Without this condition, nothing true can happen.'],
    relatedTemperaments: ['ritual_dependency', 'fragile_discipline'],
    associatedVoices: ['skeptic', 'witness', 'archivist'],
  },
  {
    id: 'success_masks_damage',
    label: 'Success Masks Damage',
    description: 'Output is still rising, so the hidden cost is being ignored or excused.',
    triggers: ['success', 'productive', 'high output', 'winning', '成功', '高产', '产出', '厉害'],
    signals: ['damage', 'cost', 'collapse', 'exhausted', 'burnout', '代价', '崩', '透支', '损耗'],
    upside: ['Can sustain momentum through difficult stretches.'],
    downside: ['The climb hides structural failure.', 'Damage becomes visible only after it is expensive.'],
    falseBeliefs: ['If it still works, it must be healthy.', 'Momentum cancels cost.'],
    relatedTemperaments: ['collapse_blindness', 'charismatic_instability'],
    associatedVoices: ['skeptic', 'body', 'cartographer'],
  },
  {
    id: 'mythic_self_narration',
    label: 'Mythic Self-Narration',
    description: 'The self is being narrated as destiny, legend, exception, or chosen role.',
    triggers: ['destiny', 'genius', 'legend', 'chosen', 'myth', '命中注定', '天才', '传奇', '神话'],
    signals: ['i am', 'my story', 'identity', '我是', '我的故事', '身份', '注定'],
    upside: ['Can create force, continuity, and bold commitment.'],
    downside: ['Story starts overriding evidence.', 'Self-description becomes an alibi.'],
    falseBeliefs: ['The story proves the method.', 'Exceptional identity exempts me from cost.'],
    relatedTemperaments: ['mythic_self_narration', 'control_hunger'],
    associatedVoices: ['archivist', 'skeptic', 'threshold'],
  },
  {
    id: 'work_more_coherent_than_life',
    label: 'Work More Coherent Than Life',
    description: 'The work carries more order, form, and clarity than the surrounding life can hold.',
    triggers: ['work', 'project', 'piece', 'output', '作品', '项目', '产出'],
    signals: ['life', 'mess', 'collapse', 'chaos', '生活', '混乱', '失衡', '崩'],
    upside: ['Can create extraordinarily clear artifacts.', 'Lets the work become a stabilizing geometry.'],
    downside: ['The artifact hides the life gap.', 'Order in the work may postpone order in reality.'],
    falseBeliefs: ['If the work is coherent, I am coherent.', 'The artifact settles the life behind it.'],
    relatedTemperaments: ['obsessive_iteration', 'fragile_discipline'],
    associatedVoices: ['cartographer', 'body', 'witness'],
  },
  {
    id: 'false_causality_after_breakthrough',
    label: 'False Causality After Breakthrough',
    description: 'A breakthrough happened during chaos, so the chaos is now mistaken for the cause.',
    triggers: ['breakthrough', 'after that', 'since then', 'because of', '突破', '自从那次', '后来', '因为'],
    signals: ['chaos', 'mess', 'high', 'drunk', '乱', '混乱', '失控', '刺激'],
    upside: ['Captures moments of genuine rupture and openness.'],
    downside: ['Confuses correlation with method.', 'Can reproduce noise while waiting for brilliance.'],
    falseBeliefs: ['The mess caused the insight.', 'Recreating the conditions recreates the gift.'],
    relatedTemperaments: ['novelty_seeking', 'collapse_blindness'],
    associatedVoices: ['skeptic', 'pattern-reader', 'archivist'],
  },
];

export const EVOLUTIONARY_BIASES: EvolutionaryBias[] = [
  {
    id: 'bias_pain_transmutation',
    description: 'Keep the expressive gain of pain-transmutation while refusing to treat injury as a required engine.',
    whenToIncrease: ['The work is emotionally dead but still structurally competent.', 'The user needs form that can carry pressure.'],
    whenToSuppress: ['Pain is being defended as method.', 'The user is aestheticizing harm instead of naming cost.'],
    associatedVoices: ['poet', 'skeptic', 'body'],
    riskNotes: ['Can slide into glamorous damage if left unchecked.'],
  },
  {
    id: 'bias_ritual_separation',
    description: 'Separate useful ritual from dependency mythology.',
    whenToIncrease: ['The user benefits from consistent entry conditions.', 'The workflow needs cleaner activation.'],
    whenToSuppress: ['The ritual is being treated as identity or talent.', 'The support condition is replacing direct work.'],
    associatedVoices: ['witness', 'skeptic', 'archivist'],
    riskNotes: ['Too much suppression can flatten valid craft rituals.'],
  },
  {
    id: 'bias_damage_visibility',
    description: 'Track life-cost alongside output so success cannot hide structural damage.',
    whenToIncrease: ['Output is high and the user is still reflective.', 'The system sees repeated overextension.'],
    whenToSuppress: ['The work requires a short burst without extra introspection.'],
    associatedVoices: ['body', 'skeptic', 'cartographer'],
    riskNotes: ['Can become moralizing if it loses contact with craft.'],
  },
  {
    id: 'bias_demythologization',
    description: 'Reduce self-mythology and prefer evidence over destiny narration.',
    whenToIncrease: ['The self-story is outrunning the actual work.', 'The narrative is becoming an alibi.'],
    whenToSuppress: ['The user needs courage, not immediate debunking.'],
    associatedVoices: ['skeptic', 'archivist', 'threshold'],
    riskNotes: ['Too much demythologization can drain momentum.'],
  },
  {
    id: 'bias_life_work_delta',
    description: 'Keep the system aware of the gap between coherent work and incoherent life.',
    whenToIncrease: ['The artifact is clean but the supporting life is unraveling.', 'The user repeatedly produces clarity from instability.'],
    whenToSuppress: ['The task needs pure making before reflection.'],
    associatedVoices: ['cartographer', 'body', 'witness'],
    riskNotes: ['Can over-center life hygiene in moments that need output.'],
  },
  {
    id: 'bias_false_causality_guard',
    description: 'Guard against confusing chaos-adjacent breakthroughs with valid repeatable method.',
    whenToIncrease: ['A breakthrough is being mythologized into method.', 'The system sees repeated folklore around conditions and genius.'],
    whenToSuppress: ['The user needs open exploration before formalization.'],
    associatedVoices: ['skeptic', 'pattern-reader', 'archivist'],
    riskNotes: ['Can become too cold if every rupture is dismissed as noise.'],
  },
];
